name: robo_app
description: The official Robo Racing League Mobile Application

version: 0.0.1+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^0.13.0+1 # https://pub.dartlang.org/packages/cloud_firestore

  cupertino_icons: ^0.1.2

  get_it: ^3.0.3 # https://pub.dartlang.org/packages/get_it
  flavor_banner:
    git: git://github.com/muldec/flavor_banner.git

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

