name: Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  BUILD_FLAVOR: prod
  JAVA_VERSION: '12.x'

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: android
          - os: macos-latest
            target: ios

    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone repo
        uses: actions/checkout@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Install Flutter stable
        uses: subosito/flutter-action@v1.1.1
        with:
          channel: stable

      - name: Get Dependencies
        run: flutter pub get

      - name: Build ${{ matrix.target }}
        run: .github/workflows/build-${{ matrix.target }}.sh $BUILD_FLAVOR
