name: Tests

on:
  push:
    branches:
      - master
      - develop
      - adapt-firebase-flavors
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: macos-latest

    env:
      BUILD_FLAVOR: prod

    steps:
      - name: Clone repo
        uses: actions/checkout@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Install Flutter stable
        uses: subosito/flutter-action@v1.1.1
        with:
          channel: stable

      - name: Get Dependencies
        run: flutter pub get

      - name: Launch Test suite
        run: flutter test

      - name: Create dummy google-services file required by Firestore at build time
        run: |
          mv android/app/src/$BUILD_FLAVOR/google-services.dummy android/app/src/$BUILD_FLAVOR/google-services.json
          mv ios/Runner/GoogleService-Info.dummy ios/Runner/GoogleService-Info.plist

      - name: Build Android
        env:
          BUILD_TARGET: appbundle
        run: flutter build $BUILD_TARGET --profile --flavor=$BUILD_FLAVOR --target=lib/main_$BUILD_FLAVOR.dart

      - name: Build iOS
        env:
          BUILD_TARGET: ios
        run: flutter build $BUILD_TARGET --profile --flavor=$BUILD_FLAVOR --target=lib/main_$BUILD_FLAVOR.dart --no-codesign
